### ISSUE TITLE
Fragment Shader compilation : 'varying out' syntax error (💲 3)

### ISSUE THREAD

**Issue by BSoDium** [photonsquid/7map#23]
Keyword varying out in src/main/java/resources/Fragment.glsl is not recognized on some computers.

**Comment by l3alr0g** [comment]
Temporary fix, GLSL version 430 can work without the `varying` keyword so I basically removed it. I won't close the issue until I get absolute confirmation that the problem doesn't occur anymore on anyone's machine.
