### ISSUE TITLE
NullPointerException in com.sevenmap.data.styles.Styles.findStyle

### ISSUE THREAD

**Issue by BSoDium** [photonsquid/7map#60]
A NullPointerException is raised in the findStyle(...) method of class com.sevenmap.data.styles.Styles, as the themes attribute is null and hasn't been instanciated. Please fix this as soon as possible, and edit the associated release (tag 0.3 3e1811bff4e98c39752ccbed0c9600cf8ef2dcf5) as soon as possible @seba1204 .

**Comment by seba1204** [comment]
This errror is fixed, but you may have another weird error from jackson, just delete the file `~/.7map/styles.json` and reopen the jar.
It happens if you have an corrupted, or an old `styles.json`. I will handle this error later. I leave this issue opened for now.

**Comment by l3alr0g** [comment]
Someone should probably create an issue related to exception handling when it comes to corrupt Style.json file loading . That's good to know, I'm keeping it open then, as requested.
